name: tidyweather
description: A weather app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_design_icons_flutter: ^3.4.4795
  http: ^0.12.0+3
  geolocator: ^5.1.5
  jiffy: ^2.1.2
  flutter_map: any
  latlong: ^0.6.1
  provider: ^4.0.1
  preferences: ^5.0.2
  url_launcher: ^5.4.1
  background_fetch: ^0.5.4
  flutter_launcher_icons: ^0.7.4
  tuple: ^1.0.3
  flutter_svg: ^0.17.1
  flip_card: ^0.4.4

flutter_icons:
  image_path: "assets/images/icon-512.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFC108"
  adaptive_icon_foreground: "assets/images/icon-foreground-512.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - config.json
    - assets/icons/
