name: tidyweather
description: A weather app.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0"

dependencies:
  flutter:
    sdk: flutter

  background_fetch: ^0.6.0
  flip_card: ^0.4.4
  flutter_launcher_icons: ^0.8.1
  flutter_map: ^0.10.1
  flutter_svg: ^0.19.1
  geocoding: ^1.0.5
  geolocator: ^6.1.4
  gradient_app_bar: ^0.1.3
  http: ^0.12.2
  jiffy: ^3.0.1
  latlong: ^0.6.1
  material_design_icons_flutter: ^4.0.5755
  preferences: ^5.2.1
  provider: ^4.3.2
  tuple: ^1.0.3
  url_launcher: ^5.7.10

flutter_icons:
  image_path: "assets/images/icon-512.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFC108"
  adaptive_icon_foreground: "assets/images/icon-foreground-512.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - config.json
    - assets/icons/generated/
