name: tidyweather
description: A weather app.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0"

dependencies:
  background_fetch: 1.0.0-nullsafety.1
  ffi: 1.0.0
  flip_card: 0.4.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.9.0
  flutter_map:
    git:
      url: git://github.com/pento/flutter_map.git
      ref: try/fast-tile-replace
  flutter_svg: 0.21.0-nullsafety.0
  geocoding: 2.0.0
  geolocator: 7.0.1
  gradient_app_bar:
    git:
      url: git://github.com/TinyProgrammers/GradientAppBar.git
  http: 0.13.1
  jiffy: 4.1.0
  latlong: 0.6.1
  material_design_icons_flutter: 5.0.5955-rc.1
  pedantic: 1.11.0
  preferences: 5.2.1
  provider: 5.0.0
  tuple: 1.0.2
  url_launcher: 6.0.3

flutter_icons:
  image_path: "assets/images/icon-512.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFC108"
  adaptive_icon_foreground: "assets/images/icon-foreground-512.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# When we need to use git dependencies, avoid showing a lint warning.
publish_to: none

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - config.json
    - assets/icons/generated/
